name: release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and create release
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          tag_name=${{ github.ref_name }}
          release_name=$tag_name

          ./bin/create-release $tag_name

          # Delete release if it already exists.
          gh release view $release_name 2>&1 > /dev/null && gh release delete $release_name --yes
          # The package name contains the tag name with any leading `dev-` removed
          gh release create $release_name --verify-tag --generate-notes *-${tag_name#dev-}.tar.gz
        shell: bash
